clean: true

theme: fullwidth

output: docs
source_directory: Sources
readme: README.md

module: SimpleFormatting
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/simple-formatting

author: ser.soft GmbH
author_url: https://sersoft.de
