name: Publish Documentation

on:
  release:
    types:
      - published
      - edited
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-and-publish-docs:
    uses: sersoft-gmbh/oss-common-actions/.github/workflows/swift-generate-and-publish-docs.yml@main
    with:
      os: ubuntu
      swift-version: '6.1'
      organisation: ${{ github.repository_owner }}
      repository: ${{ github.event.repository.name }}
      pages-branch: gh-pages
      # This is a workaround since Swift ships ICU headers that aren't aligned with the installed ICU package.
      # Apparently, on recent macOS runners, icu is also not aligned...
      before-run: |
        if [ "${IS_IN_CONTAINER:-}" -eq 1 ]; then
          apt-get update -qq && apt-get -q install -y --reinstall libicu-dev
        else
          brew update && brew install icu4c || exit 0
        fi
